spring.application.name=company-service
server.port=8082

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:company_db}
spring.datasource.username=${DB_USER:franco}
spring.datasource.password=${DB_PASSWORD:franco123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api
